[project]
name = "common-util"
version = "0.1.0"
description = "Common utilities for the NPUCompute project."
authors = [
    { name = "lbroglio", email = "lukebroglio@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "openvino>=2026.3.1",
    "torch>=2.13.0",
]

[project.scripts]
common-util = "common_util:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
