[project]
name = "input-generator"
version = "0.1.0"
description = "A Python package for generating input data for testing and experimenting with NPUCompute."
authors = [
    { name = "lbroglio", email = "lukebroglio@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "common-util",
]

[project.scripts]
input-generator = "input_generator:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
common-util = { workspace = true }
